### ISSUE TITLE
The hardware did not show up

### ISSUE THREAD

**Issue by LuqmanNazar** [mathworks/Navigating-Ryze-Tello-Drones-With-MATLAB-App#1]
May I know why my MATLAB cannot detect the hardware drone? I already follow the instruction, but it still don't work. I also already connect to laptop through WIFI.

**Comment by AstaragC** [comment]
You can try troubleshooting the issue following the below mentioned page:
https://www.mathworks.com/help/supportpkg/ryzeio/troubleshooting-in-matlab-support-package-for-ryze-tello-drones.html

If the issue persists please reach out to us creating a service request:
https://www.mathworks.com/support/contact_us.html
